### ISSUE TITLE
Fix the frontend build errors (see the frontend build logs)

### ISSUE THREAD

**Issue by elisescu** [Metaculus/metaculus#1022]
We get errors like these in the frontend build logs:
```
#24 132.6 n [Error]: Dynamic server usage: Route /help/scores-faq/ couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
#24 132.6     at l (/app/front_end/.next/server/chunks/9085.js:1:58682)
#24 132.6     at d (/app/front_end/.next/server/chunks/6005.js:24:49081)
#24 132.6     at a (/app/front_end/.next/server/app/(main)/accounts/change-email/route.js:1:5638)
#24 132.6     at d (/app/front_end/.next/server/app/(main)/accounts/change-email/route.js:1:6641)
#24 132.6     at p (/app/front_end/.next/server/app/(main)/accounts/change-email/route.js:1:7115)
#24 132.6     at f.getBulletins (/app/front_end/.next/server/chunks/409.js:1:1417)
#24 132.6     at g (/app/front_end/.next/server/chunks/409.js:1:1671)
#24 132.6     at /app/front_end/.next/server/chunks/409.js:1:24705
#24 132.6     at eh (/app/front_end/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134657)
#24 132.6     at e (/app/front_end/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:137542) {
#24 132.6   description: "Route /help/scores-faq/ couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error",
#24 132.6   digest: 'DYNAMIC_SERVER_USAGE'
#24 132.6 }
```

Should be fixed.

**Comment by ncarazon** [comment]
The issue was mostly caused by error boundary which didn't ignore `DYNAMIC_SERVER_USAGE` error (when it should). Should be fine now.
